### ISSUE TITLE
Wrong link in typepak readme

### ISSUE THREAD

**Issue by ZoeArch** [ImStuBTW/typeboy_and_typepak#1]
in `typepak/README.md` the line 41 the link to the shift register is instead a duplicate of line 40's link to the 300 OHM Ferrite Beads

**Comment by ZoeArch** [comment]
the correct link should be https://www.digikey.com/en/products/detail/texas-instruments/SN74HC595DT/1571266, as this is the link provided in the blog post

**Comment by ImStuBTW** [comment]
Thanks, the link's been updated!
